services:
  hand-gesture-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro  # Read-only model files
      - ./tests:/app/tests:ro    # Tests for development
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: hand-gesture-network
